dashboard/urls.py
from django.urls import path

from . import views

urlpatterns =[
    path('user/', views.userdash, name='userdash'),
    path('cancelorder/', views.cancelorder, name='cancelorder'),
    path('homeowner/', views.hodash, name='hodash'),
    path('changestatus/', views.changestatus, name='changestatus'),
    path('editflat/<int:flat_id>', views.editflat, name='editflat'),
    path('vieworder/<int:flat_id>', views.vieworder, name='vieworder'),
    path('editflats/', views.editflats, name='editflats'),
    path('pdfreport/', views.render_pdf_view, name='pdfreport'),
]

flats/urls.py
from django.urls import path

from . import views

urlpatterns =[
    path('', views.index, name='flats'),
    path('<int:flat_id>', views.flats, name='flat'),
    path('addflats/', views.addflats, name='addflats'),
]

home_rental/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include("index.urls"),name="index"),
    path('flats/', include("flats.urls"),name="flats"),
    path('house/', include("houses.urls"),name="house"),
    path('accounts/', include("accounts.urls"),name="accounts"),
    path('dashboard/', include("dashboard.urls"),name="dashboard"),
    path('reservation/', include("reservations.urls"),name="reservation"),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.

flats/models.py
from django.db import models
from houses.models import House

# Create your models here.
class Flat(models.Model):
    FLAT_STATUS = ( 
    ("1", "available"), 
    ("2", "not available"),    
    ) 

    FLAT_TYPE = ( 
    ("1", "Premium"), 
    ("2", "Deluxe"),
    ("3","Basic"),    
    ) 

    #type,no_of_rooms,capacity,prices,Hotel
    id = models.AutoField(primary_key=True)
    house= models.ForeignKey(House, on_delete = models.CASCADE)
    flat_type = models.CharField(max_length=50,choices = FLAT_TYPE)
    price = models.IntegerField()
    status = models.CharField(choices =FLAT_STATUS,max_length = 15)
    flatnumber = models.CharField(max_length=20)
    description = models.TextField(blank=True)
    bedrooms = models.IntegerField()
    bathrooms = models.DecimalField(max_digits=2, decimal_places=1)
    garage = models.IntegerField(default=0)
    sqft = models.IntegerField()
    rent_status = models.BooleanField(default=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)

    def __str__(self):
        return self.flatnumber

reservations/models.py
from django.db import models
from flats.models import Flat
from accounts.models import CustomUser
from month.models import MonthField

# Create your models here.
class Reservation(models.Model):
    Reservation_STATUS = ( 
    ("1", "Pending"), 
    ("2", "Approved"),
    ("3", "Canceled"),      
    ) 
    Payment_STATUS = ( 
    ("1", "Pending"), 
    ("2", "Paid"),
    ("3", "Due"),      
    ("4", "Canceled"),      
    ) 
    Police_verification_STATUS = ( 
    ("1", "Pending"), 
    ("2", "Approved"),    
    ("3", "Canceled"),      
    ) 
    id = models.AutoField(primary_key=True)
    status=models.CharField(choices=Reservation_STATUS, max_length=15, default="Pending")
    check_in = MonthField("Month Value", help_text="some help...")
    check_out = MonthField("Month Value", help_text="some help...")
    flat = models.ForeignKey(Flat, on_delete = models.CASCADE)
    guest = models.ForeignKey(CustomUser, on_delete= models.CASCADE)
    amount = models.IntegerField(null=True)
    payment_number=models.CharField(max_length=20, null=True)
    trxid=models.CharField(max_length=250, null=True)
    paymentStatus=models.CharField(choices=Payment_STATUS, max_length=15, default="Pending")
    nid = models.IntegerField(null=True)
    nationality = models.CharField(max_length=250, null=True)
    marital_status = models.CharField(max_length=250, null=True)
    father_name = models.CharField(max_length=250, null=True)
    mother_name = models.CharField(max_length=250, null=True)
    policeStatus=models.CharField(choices=Police_verification_STATUS, max_length=15, default="Pending")

    def __str__(self):
        return self.flat.flatnumber
    

dashboard/views.py
from django.shortcuts import render, redirect, get_object_or_404
from reservations.models import Reservation
from houses.models import House
from flats.models import Flat
from django.contrib import messages
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa



# Create your views here.
@login_required()
@user_passes_test(lambda u: u.groups.filter(name='user').exists())
def userdash(request):
    user = request.user.id
    reservation = Reservation.objects.order_by('-id').filter(guest_id = user)
    context = {
        'reservation':reservation,
    }
    return render(request, 'dashboard/userdash.html', context)



@login_required()
@user_passes_test(lambda u: u.groups.filter(name='user').exists() or u.groups.filter(name='Home_owner').exists())
def cancelorder(request):
    if request.method == 'POST':
        id = request.POST['reservationid']
        order = Reservation.objects.get(id=id)
        flat = Flat.objects.filter(id=order.flat_id)
        flat.update(rent_status=True)
        Reservation.objects.filter(id=id).delete()
        messages.success(request,"Reservation Canceled Successfully")
        return redirect(request.META['HTTP_REFERER'])



@login_required()
@user_passes_test(lambda u: u.groups.filter(name='Home_owner').exists())
def hodash(request):
    user = request.user
    houses = House.objects.filter(owner=user)
    totall_flats = []
    total_reserved = []
    for house in houses:
        flats = Flat.objects.filter(house=house)
        for flat in flats:
            reserved = Reservation.objects.order_by('-id').filter(flat=flat)
            total_reserved += reserved
        totall_flats += flats           
    flats_length = len(totall_flats)
    available_flats = Flat.objects.filter(rent_status=True)
    context = {
        'houses':houses,
        'houses_length':len(houses),
        'flats':totall_flats,
        'flats_length':flats_length,
        'available_flats':available_flats,
        'length_available_flats':len(available_flats),
        'reserved':total_reserved,
        'reserved_length':len(total_reserved),

    }
    return render(request, 'dashboard/hodash.html', context)


@login_required()
@user_passes_test(lambda u: u.groups.filter(name='Home_owner').exists())
def changestatus(request):
    if request.method == 'POST':
        reservation = Reservation.objects.filter(id = request.POST['reservationid'])
        if 'policeStatus' in request.POST:
            reservation.update(policeStatus = request.POST['policeStatus'])
        if 'paymentStatus' in request.POST:
            reservation.update(paymentStatus = request.POST['paymentStatus'])
        if 'status' in request.POST:
            reservation.update(status = request.POST['status'])

        messages.success(request,"Status Updated Successfully")
        return redirect(request.META['HTTP_REFERER']) 



@login_required()
@user_passes_test(lambda u: u.groups.filter(name='Home_owner').exists())
def vieworder(request, flat_id):
    reservation = Reservation.objects.filter(flat_id=flat_id).first()
    if reservation:
        context = {
            'reservation' : reservation,
        }
        return render(request,'dashboard/vieworder.html', context)
    else:
        messages.success(request,"It's Not Booked Yet")
        return redirect(request.META['HTTP_REFERER'])



@login_required()
@user_passes_test(lambda u: u.groups.filter(name='Home_owner').exists())
def editflat(request, flat_id):
    flat = get_object_or_404(Flat, pk=flat_id)
    context = {
    'flat': flat,
    }
    return render(request, 'dashboard/editflat.html', context)



@login_required()
@user_passes_test(lambda u: u.groups.filter(name='Home_owner').exists())
def editflats(request):
    if request.method == 'POST':
        flat = Flat.objects.filter(id = request.POST['flatid'])
        if 'flatnumber' in request.POST:
            flat.update(flatnumber = request.POST['flatnumber'])
        if 'flattype' in request.POST:
            flat.update(flat_type = request.POST['flattype'])
        if 'price' in request.POST:
            flat.update(price = request.POST['price'])
        if 'status' in request.POST:
            flat.update(status = request.POST['status'])
        if 'bedrooms' in request.POST:
            flat.update(bedrooms = request.POST['bedrooms'])
        if 'bathrooms' in request.POST:
            flat.update(bathrooms = request.POST['bathrooms'])
        if 'garage' in request.POST:
            flat.update(garage = request.POST['garage'])
        if 'size' in request.POST:
            flat.update(sqft = request.POST['size'])
        if 'description' in request.POST:
            flat.update(description = request.POST['description'])
        if 'image' in request.FILES:
            flat.update(photo_main = request.POST['image'])
        
        messages.success(request,"Status Updated Successfully")
        return redirect(request.META['HTTP_REFERER'])




@login_required()
@user_passes_test(lambda u: u.groups.filter(name='Home_owner').exists())
def render_pdf_view(request):
    user = request.user
    houses = House.objects.filter(owner=user)
    totall_flats = []
    total_reserved = []
    for house in houses:
        flats = Flat.objects.filter(house=house)
        for flat in flats:
            reserved = Reservation.objects.order_by('-id').filter(flat=flat)
            total_reserved += reserved
        totall_flats += flats           
    flats_length = len(totall_flats)
    available_flats = Flat.objects.filter(rent_status=True)
    template_path = 'dashboard/report.html'
    context = {
        'user': user,
        'houses':houses,
        'houses_length':len(houses),
        'flats':totall_flats,
        'flats_length':flats_length,
        'available_flats':available_flats,
        'length_available_flats':len(available_flats),
        'reserved':total_reserved,
        'reserved_length':len(total_reserved), 
    }
    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    response['Content-Disposition'] = 'filename="report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
       html, dest=response)
    # if error then show some funy view
    if pisa_status.err:
       return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

templates/dashboard/editflat.html
{% extends 'base.html' %}
{% block title %}Edit Flat
{% endblock title %}
{% block content %}

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'hodash' %}">
              <i class="fas fa-home"></i> Dashboard</a>
          </li>
          <li class="breadcrumb-item active"> Edit Flat</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Alerts -->
  {% include 'partials/_alerts.html' %}


<h1 class="text-center bg-warning my-0">Edit Flat</h1>
    <!--Staff section -->
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-lg-6 col-xlg-6 col-sm-12 mx-auto">
                <form action="{% url 'editflats' %}" method="POST" enctype="multipart/form-data">
                    {%csrf_token%}
                    <div class="form-group">
                        <label for="housename">House Name:</label>
                        <input type="text" class="form-control" id="housename" name="housename" value="{{flat.house.name}}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="flatnumber">Flat Number:</label>
                        <input type="text" class="form-control" id="flatnumber" name="flatnumber" value="{{flat.flatnumber}}">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Status:</label>
                        <select class="form-control" name="status" id="status">
                            <option value="1">Available</option>
                            <option value="2">Not Available</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="email">Flat Type:</label>
                        <select class="form-control" name="flattype" id="flattype">
                            <option  value='1'>Premium</option>
                            <option  value='2'>Deluxe</option>
                            <option  value='3'>Basic</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="bedrooms">Bedroom:</label>
                        <input type="number" class="form-control " id="bedrooms" name="bedrooms" value="{{flat.bedrooms}}">
                    </div>
                    <div class="form-group">
                        <label for="bathrooms">Bathrooms:</label>
                        <input type="number" class="form-control " id="bathrooms" name="bathrooms" value="{{flat.bathrooms}}">
                    </div>
                    <div class="form-group">
                        <label for="garage">Garage:</label>
                        <input type="number" class="form-control " id="garage" name="garage" value="{{flat.garage}}">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Price:</label>
                        <input type="mumber" class="form-control " id="price" name="price" value="{{flat.price}}">
                    </div>
                    <div class="form-group">
                        <label for="pwd">Size:</label>
                        <input type="number" class="form-control " id="size" name="size" value="{{flat.sqft}}">
                    </div>
                    <div class="form-group">
                        <label for="description">Description:</label>
                        <textarea class="form-control " id="description" name="description" >{{flat.description}}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Location:</label>
                        <input type="text" class="form-control " id="hotel" name="hotel" value="{{flat.house.location}}" disabled>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Flat Image:</label>
                        <input type="file" class="form-control " id="image" name="image">
                    </div>
                    <button type="submit" class="btn btn-success mb-3">Save</button>
                    <input type="hidden" name="flatid" value="{{flat.id}}">
                    <input type="hidden" class="form-control " id="houseid" name="houseid" value="{{flat.house.id}}">
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

    

templates/dashboard/payments.html
{% extends 'base.html' %}

{% block title %} | Make Payment {% endblock %}

{% block content %}

<form action="{% url 'payment' %}" method="POST">
    {%csrf_token%}

    <div class="col"  style="    background: rgb(242, 242, 242);  border-radius: 20px;" >
          
        <div class="col-50">
            <h3 style="text-align: center; color: #28a745!important; padding-top: 25px; padding-bottom: 8px;"> Steps For Bkash Payment</h3>
            <ol style="border-bottom: 1px solid black; padding-bottom: 8px;">
                <li>Dial <b>*247#</b></li>
                <li>Select <b>Make Payment</b></li>
                <li>Input Mobile No: <b>01757110296</b></li>
                <li>Input Counter No: <b>1</b></li>
                <li>Input <b>PIN</b></li>
                <li><b>Confirm</b></li>
            </ol>
            </div>


            <div class="form-group">
                <label for="password2">You Need to Pay Total:</label>
                <input type="number" class="form-control " id="price" placeholder="price " name="price" disabled value={{reservation.amount}}>
            </div>

        <div class="form-group">
            <label for="pwd">Your Bkash Number:</label>
            <input type="number" class="form-control" min="1" id="number" name="bkash_number" required="True">
        </div>

        <div class="form-group">
            <label for="pwd">Trnx ID:</label>
            <input type="text" class="form-control " id="trx" name="trx" required="True">
        </div>
        <div style="text-align: center; margin-top: 15px;"><button type="submit" class="btn btn-success mb-3" >Confirm </button></div>
       
        <input type="hidden" name="reservationid" value="{{reservation.id}}">
      </div>
    </div>

</from>


{% endblock %}

templates/dashboard/report.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Report</title>
  </head>
  <body>
    
    
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="row p-5">
                            <div class="col-md-6 text-right">
                                <p class="font-weight-bold mb-1">Sabbir Home System</p>
                            </div>
                        </div>
                        <hr class="my-5">
                        <div class="row pb-5 p-5">
                            <div class="col-md-6">
                                <p class="font-weight-bold mb-4">Information</p>
                                <p class="mb-1">{{ user.first_name}} {{ user.last_name}} ({{ user.username}})</p>
                                <p>{{ user.email}}</p>
                            </div>
                        </div>

                        <h2 class="text-center text-primary">Property Status</h2>
    <div class="container-fluid px-5 py-5 border">
      <div class="row">
        <div class="col-xl-3 col-lg-6 col-sm-12 mb-4">
          <div class="bg-white rounded-lg p-5 shadow">
            <h2 class="h6 font-weight-bold text-center mb-4">Total Houses</h2>
  
           <h4 class="h6 font-weight-bold text-center mb-4">{{houses_length}}</h4>
            <!-- END -->
          </div>
        </div>
  
        <div class="col-xl-3 col-lg-6 col-sm-12 mb-4">
          <div class="bg-white rounded-lg p-5 shadow">
            <h2 class="h6 font-weight-bold text-center mb-4">Total Flats</h2>
  
            <h4 class="h6 font-weight-bold text-center mb-4">{{flats_length}}</h4>
            <!-- END -->
          </div>
        </div>
        
        <div class="col-xl-3 col-lg-6 col-sm-12 mb-4">
          <div class="bg-white rounded-lg p-5 shadow">
            <h2 class="h6 font-weight-bold text-center mb-4">Total Reserved</h2>
            
            <h4 class="h6 font-weight-bold text-center mb-4">{{reserved_length}}</h4>
            <!-- END -->
          </div>
        </div>
        
        <div class="col-xl-3 col-lg-6 col-sm-12 mb-4">
          <div class="bg-white rounded-lg p-5 shadow">
            <h2 class="h6 font-weight-bold text-center mb-4">
              Total Availables
            </h2>
            <h4 class="h6 font-weight-bold text-center mb-4">{{length_available_flats}}</h4>
  
            
            <!-- END -->
          </div>
        </div>
      </div>
    </div>
    <hr class="my-5">
                        <div class="row p-5">
                            <div class="col-md-12">
                                <table class="table table-striped ml-3 mb-3">
                                    <thead>
                                      <th>Flat Number</th>
                                      <th>House Name</th>
                                      <th>Location</th>
                                      <th>State</th>
                                      <th>Type</th>
                                      <th>Rent Status</th>
                                      <th>Availability</th>
                                      <th>Price</th>
                                      <th>BedRooms</th>
                                      <th>Size</th>
                                    
                                    </thead>
                                    {% if flats %} 
                                    {% for flat in flats %}
                                    <tr>
                                      <td>{{flat.flatnumber}}</td>
                                      <td>{{flat.house.name}}</td>
                                      <td>{{flat.house.location}}</td>
                                      <td>{{flat.house.state}}</td>
                                      <td>{{flat.get_flat_type_display}}</td>
                                      {% if flat.rent_status %}
                                      <td>Not Rented</td>
                                      {% else %}
                                      <td>Rented</td>
                                      {% endif %}
                                      <td>{{flat.get_status_display}}</td>
                                      <td>{{flat.price}}</td>
                                      <td>{{flat.bedrooms}}</td>
                                      <td>{{flat.sqft}} sqft</td>
                                    </tr>
                                    {% endfor %} 
                                    {% endif %}
                                  </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>



    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/dashboard/userdash.html
{% extends 'base.html' %}

{% block title %} | User Dashboard {% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 text-white">
    <div class="container">
      <div class="row text-center">
        <div class="col-md-12">
          <h1 class="display-4">User Dashboard</h1>
          <p class="lead">Manage your Orders</p>
        </div>
      </div>
    </div>
  </section>

  <!-- Breadcrumb -->
  <section id="bc" class="mt-3">
    <div class="container">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="{% url 'index' %}">
              <i class="fas fa-home"></i> Home</a>
          </li>
          <li class="breadcrumb-item active"> Dashboard</li>
        </ol>
      </nav>
    </div>
  </section>

  <!-- Alerts -->
  {% include 'partials/_alerts.html' %}

  <section id="dashboard" class="py-4">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Welcome {{ user.first_name }}</h2>
          {% if reservation %}
            <p>Here are the property listings that you have ordered</p>
          {% else %}
            <p>You have not ordered any flat yet</p>
          {% endif %}
        </div>
      </div>
    </div>
  </section>
  {% if reservation %}
  {% for contact in reservation %}
      {% if contact.payment_number %}
      {% else %}
  <table class="table table-striped ml-3 mb-3">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Property</th>
        <th scope="col">Check In</th>
        <th scope="col">Check Out</th>
        <th scope="col">Status</th>
        <th scope="col">Invoice</th>
        <th scope="col">Payment Status</th>
        <th scope="col">Police Verification Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>{{ contact.id }}</td>
          <td>{{ contact.flat.flatnumber}}</td>
          <td>{{ contact.check_in}}</td>
          <td>{{ contact.check_out}}</td>
          <td>{{ contact.get_status_display}}</td>
          <td>{{ contact.amount}}</td> 
          <td>{{ contact.get_paymentStatus_display}}</td>
          <td>{{ contact.get_policeStatus_display}}</td>
          <form action="{% url 'payment' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="reservationid" value="{{ contact.id }}">
            <td>
              <button type="submit" class="btn btn-warning">Make Payment</button>
            </td>
          </form>
          <form action="{% url 'cancelorder' %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="reservationid" value="{{ contact.id }}">
            <td>
              <button type="submit" class="btn btn-danger">Cancel</button>
            </td>
          </form>
          
          <td>
            <a class="btn btn-dark" href="{% url 'flat' contact.flat_id %}">View</a>
          </td>
        </tr>
      
    </tbody>
  </table>
  {% endif %}
  {% endfor %}

  {% for contact in reservation %}
      {% if contact.payment_number %}
      
  <table class="table table-striped ml-3 mb-3">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Property</th>
        <th scope="col">Check In</th>
        <th scope="col">Check Out</th>
        <th scope="col">Status</th>
        <th scope="col">Invoice</th>
        <th scope="col">Payment Number</th>
        <th scope="col">Trx ID</th>
        <th scope="col">Payment Status</th>
        <th scope="col">Police Verification Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td>{{ contact.id }}</td>
          <td>{{ contact.flat.flatnumber}}</td>
          <td>{{ contact.check_in}}</td>
          <td>{{ contact.check_out}}</td>
          <td>{{ contact.get_status_display}}</td>
          <td>{{ contact.amount}}</td> 
          <td>{{ contact.payment_number}}</td>
          <td>{{ contact.trxid}}</td>
          <td>{{ contact.get_paymentStatus_display}}</td>
          <td>{{ contact.get_policeStatus_display}}</td>
          <td>
            <a class="btn btn-dark" href="{% url 'flat' contact.flat_id %}">View</a>
          </td>
        </tr>
      
    </tbody>
  </table>
  {% endif %}
  {% endfor %}
  {% endif %}
  {% endblock %}

templates/dashboard/vieworder.html
{% extends 'base.html' %}
{% block title %}View Order
{% endblock title %}
{% block content %}

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'hodash' %}">
            <i class="fas fa-home"></i> Dashboard</a>
        </li>
        <li class="breadcrumb-item active">View Order</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'partials/_alerts.html' %}



<hr> 
<h3 class="text-success" style="text-align: center;">Booking Details</h3>
<table class="table table-striped ml-3 mb-3">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Property</th>
      <th scope="col">Check In</th>
      <th scope="col">Check Out</th>
      <th scope="col">Status</th>
      <th scope="col">Change Status</th>
      <th scope="col">Invoice</th>
      <th scope="col">Payment Status</th>
      <th scope="col">Change Payment Status</th>
      <th scope="col">Police Verification Status</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <form action="{% url 'changestatus' %}" method="POST">
        {% csrf_token %}
      <td>{{ reservation.id }}</td>
      <td>{{ reservation.flat.flatnumber}}</td>
      <td>{{ reservation.check_in}}</td>
      <td>{{ reservation.check_out}}</td>
      <td>{{ reservation.get_status_display}}</td>
      <td>
        <div class="form-group">
          <select class="form-control" name="status" id="roomtype">
            <option value="1">Pending</option>
            <option value="2">Approve</option>
            <option value="3">Cancel</option>
          </select>
        </div>
      </td>
      <td>{{ reservation.amount}}</td>
      <td>{{ reservation.get_paymentStatus_display}}</td>
      <td>
        <div class="form-group">
          <select class="form-control" name="paymentStatus" id="roomtype">
            <option value="1">Pending</option>
            <option value="2">Paid</option>
            <option value="3">Due</option>
            <option value="4">Cancel</option>
          </select>
        </div>
      </td>
      <td>{{ reservation.get_policeStatus_display}}</td>
        <td>
          <div class="form-group">
            <select class="form-control" name="policeStatus" id="roomtype">
              <option value="1">Pending</option>
              <option value="2">Approve</option>
              <option value="3">Cancel</option>
            </select>
          </div>
        </td>
        <td>
          <button type="submit" class="btn btn-primary">Submit</button>
          <input type="hidden" name="reservationid" value="{{reservation.id}}">
        </td>
      </form>
      
    </tr>
</table>
{% endblock content %}